import type { ComponentType } from 'react'
import {
  AddOne,
  Announcement,
  Application,
  ApplicationOne,
  Bank,
  Bill,
  Box,
  BuildingOne,
  Calendar,
  CalendarThirty,
  CategoryManagement,
  ChartHistogram,
  ChartPie,
  CheckOne,
  Connection,
  DashboardOne,
  Delete,
  Edit,
  Exchange,
  FileEditing,
  FileText,
  Fingerprint,
  FolderOpen,
  Gift,
  HeadsetOne,
  Help,
  History,
  IdCard,
  LinkOne,
  ListCheckbox,
  ListTwo,
  Message,
  Messages,
  PaperMoney,
  PayCode,
  PeoplePlus,
  Peoples,
  PhoneCall,
  PreviewOpen,
  Protect,
  Setting,
  SettingTwo,
  Shop,
  Shopping,
  ShoppingCart,
  Time,
  Toolkit,
  Tool,
  Translate,
  TreeDiagram,
  Truck,
  Wallet,
  Workbench,
} from '@icon-park/react'

type ParkIconComponent = ComponentType<{
  theme?: 'outline' | 'filled' | 'two-tone' | 'multi-color'
  size?: number | string
  className?: string
}>

export const NAV_ICON_MAP: Record<string, ParkIconComponent> = {
  dashboard: DashboardOne,
  corporate_fare: BuildingOne,
  store: Shop,
  account_tree: TreeDiagram,
  admin_panel_settings: SettingTwo,
  manage_accounts: Peoples,
  history: History,
  delete: Delete,
  quiz: Help,
  settings: Setting,
  help: Help,
  feedback: Messages,
  edit_document: FileEditing,
  headphones: HeadsetOne,
  build: Toolkit,
  home_repair_service: Tool,
  add_circle: AddOne,
  fact_check: CheckOne,
  receipt_long: PaperMoney,
  payments: PayCode,
  receipt: Bill,
  phone_in_talk: PhoneCall,
  account_balance: Bank,
  inventory_2: Box,
  add_box: AddOne,
  group: Peoples,
  groups: Peoples,
  person_add: PeoplePlus,
  local_shipping: Truck,
  summarize: ListTwo,
  list_alt: ListTwo,
  edit_note: Edit,
  swap_horiz: Exchange,
  link: LinkOne,
  assessment: ChartHistogram,
  savings: Wallet,
  badge: IdCard,
  schedule: Time,
  fingerprint: Fingerprint,
  event_busy: CalendarThirty,
  category: CategoryManagement,
  calendar_month: Calendar,
  celebration: Gift,
  account_balance_wallet: Wallet,
  folder_shared: FolderOpen,
  hub: Connection,
  event: Calendar,
  task: ListCheckbox,
  call: PhoneCall,
  campaign: Announcement,
  description: FileText,
  shopping_cart: ShoppingCart,
  extension: Application,
  analytics: ChartPie,
  visibility: PreviewOpen,
  language: Translate,
  point_of_sale: Shopping,
  chat: Message,
  shield: Protect,
  widgets: ApplicationOne,
  work: Workbench,
}
